export {default as Article} from './article/Article'
export {default as Brand} from './brand/Brand'
export {default as Feauture } from './feauture/Feauture'
export {default as CallToAction} from './cta/CallToAction'
export {default as Navbar} from './navbar/Navbar'
